# Generated by Django 5.0.1 on 2025-07-27 17:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Modelo')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2030)], verbose_name='Ano')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço (MZN)')),
                ('mileage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quilometragem')),
                ('fuel', models.CharField(choices=[('Gasolina', 'Gasolina'), ('Diesel', 'Diesel')], default='Gasolina', max_length=20, verbose_name='Combustível')),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automática', 'Automática'), ('CVT', 'CVT'), ('Semi-automática', 'Semi-automática')], default='Manual', max_length=20, verbose_name='Transmissão')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Cor')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Localização')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='categories.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/', verbose_name='Imagem')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Imagem Principal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car', verbose_name='Carro')),
            ],
            options={
                'verbose_name': 'Imagem do Carro',
                'verbose_name_plural': 'Imagens dos Carros',
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
    ]
