# Generated by Django 4.2.7 on 2025-08-01 23:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1975), django.core.validators.MaxValueValidator(2030)], verbose_name='Ano'),
        ),
    ]
