# Generated by Django 5.1.7 on 2025-07-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Texto Alternativo'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(upload_to='cars/%Y/%m/', verbose_name='Imagem'),
        ),
    ]
