# Generated by Django 4.2.7 on 2025-08-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('subject', models.CharField(choices=[('info_vehicles', 'Informações sobre veículos'), ('test_drive', 'Agendamento de test drive'), ('financing', 'Financiamento e parcelas'), ('sell_car', 'Venda do meu carro'), ('support', 'Suporte pós-venda'), ('partnership', 'Parcerias comerciais'), ('other', 'Outros assuntos')], max_length=50, verbose_name='Assunto')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('preferred_contact', models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('phone', 'Telefone'), ('email', 'E-mail')], max_length=20, null=True, verbose_name='Preferência de Contato')),
                ('status', models.CharField(choices=[('new', 'Nova'), ('in_progress', 'Em Andamento'), ('resolved', 'Resolvida'), ('closed', 'Fechada')], default='new', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=20, verbose_name='Prioridade')),
                ('admin_response', models.TextField(blank=True, null=True, verbose_name='Resposta do Administrador')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Data da Resposta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
            ],
            options={
                'verbose_name': 'Mensagem de Contato',
                'verbose_name_plural': 'Mensagens de Contato',
                'ordering': ['-created_at'],
            },
        ),
    ]
